apiVersion: v1
kind: Service
metadata:
  name: simple-ml-app-service
spec:
  type: NodePort
  selector:
    app: simple-ml-app
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 33080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-ml-app-deployment
  labels:
    app: simple-ml-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-ml-app
  template:
    metadata:
      labels:
        app: simple-ml-app
    spec:
      containers:
      - name: simple-ml-app
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
